### ISSUE TITLE
Version 6.2 and detect.py with onnx & dnn : problems dependent on pytorch version.

### ISSUE THREAD

**Issue by wvalcke** [ultralytics/yolov5#10304]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Running detect.py
python detect.py --weights best.onnx --dnn

cv2.error: OpenCV(4.6.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'handleNode'
> Node [Identity@ai.onnx]:(onnx_node!Identity_0) parse error: OpenCV(4.6.0) /io/opencv/modules/dnn/src/layer.cpp:246: error: (-215:Assertion failed) inputs.size() in function 'getMemoryShapes'

The issue is that the onnx export is going wrong depending on the used pytorch version
1.11.0 : works
1.12.1: does not work
Where is the problem located ? OpenCV, Pytorch, Yolov5 ??

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by wvalcke** [comment]
Thanks for your reply, i'll give it a try. Let you guys know when i've done the test.

**Comment by wvalcke** [comment]
I can confirm that this fix works with pytorch 1.12.1:

- Using Python (opencv-python version 4.6.0.66)
- Using C++ with opencv 4.6.0 

I can correctly read in the yolov5 model converted to onnx format. (version 6.2 of yolov5 was used to make the conversion from .pt to onnx, of course including the small fix from above)

**Comment by glenn-jocher** [comment]
@wvalcke I've added a warning in #10368. Not sure what else to do, since we want this to default to True as it results in smaller ONNX models.

**Comment by kXborg** [comment]
> I can confirm that this fix works with pytorch 1.12.1:
> 
> * Using Python (opencv-python version 4.6.0.66)
> * Using C++ with opencv 4.6.0
> 
> I can correctly read in the yolov5 model converted to onnx format. (version 6.2 of yolov5 was used to make the conversion from .pt to onnx, of course including the small fix from above)

Hi @wvalcke ,

What is the working version of onnx? 1.13.0 and 1.12.0 are not working for me.
