### ISSUE TITLE
How to train with multi-GPU?

### ISSUE THREAD

**Issue by xjohnxjohn** [ultralytics/yolov5#115]
Hi Glenn-jocher, I run command "python train.py --data data/coco128.yaml --cfg models/yolov5s.yaml --weights '' --batch-size 16 --device '0,1', It show error "Single-Process Multi-GPU is not the recommended mode for".

How I use mutli-gpu to train?

**Comment by glenn-jocher** [comment]
@xjohnxjohn your environment may not be set up correctly. You could try our docker image below to see if you can reproduce the same error there:

## Reproduce Our Environment

To access an up-to-date working environment (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled), consider a:

- **GCP** Deep Learning VM with $300 free credit offer: See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Google Colab Notebook** with 12 hours of free GPU time. <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/)

**Comment by yxNONG** [comment]
@xjohnxjohn i meet the same problem, seems like it cause by the pytorch1.5 
i  use 
`model = torch.nn.DataParallel(model)`
to replace the 
`model = torch.nn.parallel.DistributedDataParallel(model) `

@glenn-jocher, i remember you mention this problem in yolov3, 
but i'm not sure that yolov5 will work on pytorch1.4

**Comment by xjohnxjohn** [comment]
@yxNONG @glenn-jocher Great, thank you.

**Comment by AIFAN-Lab** [comment]
@xjohnxjohn I have tried it with pytorch1.4, it runs very well without any change.

**Comment by zengjianyou** [comment]
but i use model = torch.nn.DataParallel(model)  to replace   
model = torch.nn.parallel.DistributedDataParallel(model)
other error have happen：
Traceback (most recent call last):
  File "pytorch-yolov5/train.py", line 407, in <module>
    train(hyp)
  File "pytorch-yolov5/train.py", line 210, in train
    check_best_possible_recall(dataset, anchors=model.model[-1].anchor_grid, thr=hyp['anchor_t'], imgsz=imgsz)
  File "python3.7/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'model'
@yxNONG @glenn-jocher

**Comment by glenn-jocher** [comment]
@zengjianyou this issue is already resolved a couple days ago. Git pull to get the latest code including this fix.

**Comment by yxNONG** [comment]
@zengjianyou 
my code is the version pull at 6.12
what i did is replace  
`dist.init_process_group(....) `
`model = torch.nn.parallel.DistributedDataParallel(model)`
by
`model = torch.nn.DataParallel(model)`

and remove the code
`dist.destroy_process_group() if torch.cuda.device_count() > 1 else None`
before
`return results`

________________________________________________________
Beside, i try to run the code in pytorch1.4 with 4GPU
`model = torch.nn.parallel.DistributedDataParallel(model) `
 it work but the ap is about 1/4 of the ap train with 1GPU, 
seems like it just report the result in 1GPU (so the result is 1/4 )
@glenn-jocher is the latest version fix this?

**Comment by yxNONG** [comment]
@zengjianyou 
i use pytorch 1.5 and set `mixed_precision = False`  all the time

**Comment by zengjianyou** [comment]
> @zengjianyou this issue is already resolved a couple days ago. Git pull to get the latest code including this fix.

ok

**Comment by zengjianyou** [comment]
i use latest  code ,and use:      
model = torch.nn.DataParallel(model)
have other error:
Traceback (most recent call last):
  File "/home/zjy/pycharm_work/pytorch-yolov5/other_train.py", line 405, in <module>
    train(hyp)
  File "/home/zjy/pycharm_work/pytorch-yolov5/other_train.py", line 307, in train
    fast=epoch < epochs / 2)
  File "/home/zjy/pycharm_work/pytorch-yolov5/test.py", line 102, in test
    inf_out, train_out = model(img, augment=augment)  # inference and training outputs
  File "/home/zjy/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zjy/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/zjy/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/zjy/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/zjy/miniconda3/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/zjy/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/zjy/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zjy/pycharm_work/pytorch-yolov5/models/yolo.py", line 91, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/zjy/pycharm_work/pytorch-yolov5/models/yolo.py", line 108, in forward_once
    x = m(x)  # run
  File "/home/zjy/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zjy/pycharm_work/pytorch-yolov5/models/common.py", line 21, in forward
    return self.act(self.bn(self.conv(x)))
  File "/home/zjy/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zjy/miniconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "/home/zjy/miniconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 346, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
@glenn-jocher @yxNONG  why?

**Comment by yxNONG** [comment]
@zengjianyou what's your batch_size and the GPU num?

**Comment by zengjianyou** [comment]
i solve it when i use  lastest test code ，thank you！@yxNONG

**Comment by yxNONG** [comment]
@zengjianyou you means that in latest code
`model = torch.nn.parallel.DistributedDataParallel(model)`
work, right?

**Comment by xjohnxjohn** [comment]
> @xjohnxjohn your environment may not be set up correctly. You could try our docker image below to see if you can reproduce the same error there:
> 
> ## Reproduce Our Environment
> To access an up-to-date working environment (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled), consider a:
> 
> * **GCP** Deep Learning VM with $300 free credit offer: See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Google Colab Notebook** with 12 hours of free GPU time. [![Open In Colab](https://camo.githubusercontent.com/52feade06f2fecbf006889a904d221e6a730c194/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb)
> * **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/)

I tried using Docker Image, the multi-gpu not woking also. The message show different before. (I had 2 gpu-card, RTX2080(8GB) and GTX1080Ti(11GB), the memory not the same)

**Comment by glenn-jocher** [comment]
@xjohnxjohn you should only train with identical gpus. To use cuda devices 0 and 1 for example `python train.py --device 0,1`
