### ISSUE TITLE
What can i do to solve this issue? AttributeError: module 'test' has no attribute 'test'

### ISSUE THREAD

**Issue by Floo33R** [ultralytics/yolov5#838]
## ❔Question
Hello guys!
I ran into an issue. I tried to follow this guide https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data. Everything is working fine until the first Epoch is nearly over. Then it shows the following output: 

`Traceback (most recent call last):`
  `File "train.py", line 462, in <module>`
    `train(hyp, opt, device, tb_writer)`
  `File "train.py", line 321, in train`
    `results, maps, times = test.test(opt.data, `
`AttributeError: module 'test' has no attribute 'test'`

## Additional context
I'm working on Pop_OS20.04.
For the training i use this command:
`python3 train.py --img 640 --batch 2 --epochs 5 --data ./data/coco128.yaml --cfg ./models/yolov5s.yaml --weights ''`

Thanks for the help in advance.

**Comment by glenn-jocher** [comment]
@Floo33R probably an environment issue. Recommend you run the Colab tutorials. https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

**Comment by Floo33R** [comment]
> @Floo33R probably an environment issue. Recommend you run the Colab tutorials. https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb
@glenn-jocher So there is no chance to run it on my computer with my own CPU/GPU?

**Comment by glenn-jocher** [comment]
@Floo33R of course you can run on your own computer. I'll paste our environment guidance.

it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.6`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by Floo33R** [comment]
I changed to from PopOS to Windows 10 and there it works fine.
Thanks for the help!
