### ISSUE TITLE
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

### ISSUE THREAD

**Issue by uesrs** [ultralytics/yolov5#11838]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

我在运行时出现以下错误：
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
![41c38dc9f99cd87ff5d8ee97c99c9b3f](https://github.com/ultralytics/yolov5/assets/118713813/0282e352-b429-46ed-8af5-ef737979278b)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@uesrs this issue seems to be related to a missing attribute in the `FreeTypeFont` object. However, it is difficult to determine the exact cause without additional information.

Please make sure you are using the latest version of YOLOv5, as this issue could have been resolved in a more recent release. If you are already on the latest version or the issue persists, please provide a minimal reproducible example along with the necessary steps to reproduce the error.

Once we have more information, we will be able to investigate further and provide a solution.

Thank you for your understanding and willingness to contribute!

**Comment by yifeizhangfr** [comment]
@uesrs This is caused by new version of Pillow, you can check version of pillow, if version is 10.0.0, just downgrade to pillow 9.5.

**Comment by glenn-jocher** [comment]
@yifeizhangfr, thank you for reporting this issue. It appears that the AttributeError you encountered, `'FreeTypeFont' object has no attribute 'getsize'`, is caused by a compatibility problem with the new version of Pillow.

To resolve this issue, you can try downgrading Pillow to version 9.5 if you are currently using version 10.0.0.

Please let us know if downgrading Pillow solves the problem for you. If you have any further questions or need additional assistance, feel free to ask.

Thank you for your patience and contribution!

**Comment by yifeizhangfr** [comment]
@glenn-jocher The problem has been solved.

**Comment by glenn-jocher** [comment]
@yifeizhangfr great to hear that the issue has been resolved! If you encountered any other problems or have any questions, feel free to reach out. Thanks for letting us know and happy coding!

**Comment by adamshaeffer** [comment]
Can confirm, downgrading Pillow to 9.5 works as a fix. Can we get this a commit to the requirements.txt? Or are you making a fix to work with Pillow 10.0.0?

**Comment by glenn-jocher** [comment]
@adamshaeffer thank you for bringing this to our attention. We appreciate you confirming that downgrading Pillow to version 9.5 resolves the issue. 

We will consider adding this as a recommendation in the requirements.txt file for YOLOv5. However, we also plan to investigate and address the compatibility issue with Pillow 10.0.0, which will allow users to use the latest version without encountering this problem. 

We appreciate your patience and contribution to the YOLOv5 community. If you have any further questions or concerns, please don't hesitate to ask.

**Comment by AlessSilva** [comment]
Hello! I had the same problem training YOLOv5, and I solved it by downgrading Pillow to version 9.5.

**Comment by glenn-jocher** [comment]
@AlessSilva great to hear that you were able to solve the issue by downgrading Pillow to version 9.5! Thank you for sharing your solution. We will consider adding a recommendation for this in the YOLOv5 documentation. If you have any other questions or need further assistance, feel free to ask.

**Comment by Soichi9** [comment]
There may be no impact on learning. However, the images of mosaics will no longer be saved initially.

**Comment by glenn-jocher** [comment]
@Soichi9 thank you for bringing this to our attention. While downgrading Pillow to version 9.5 can resolve the issue of `'FreeTypeFont' object has no attribute 'getsize'`, we are also actively investigating and addressing the compatibility problem with Pillow 10.0.0. 

Please note that the downgraded Pillow version does not impact the learning process, but it may affect the initial saving of mosaic images. We appreciate your feedback and patience. If you have any further questions or concerns, please don't hesitate to reach out.

**Comment by Soichi9** [comment]
@glenn-jocher　I apologize for the confusion. Pillow 10.0.0 may not affect the learning. However, the mosaic images will not be saved in the initial state. 9.5 is normal.

**Comment by glenn-jocher** [comment]
@Soichi9 i appreciate you bringing this to our attention. While Pillow version 10.0.0 may not have any impact on the learning process itself, it can cause an issue where mosaic images are not saved in the initial state. In contrast, Pillow version 9.5 does not exhibit this behavior and works normally. Thank you for your understanding and clarification.

**Comment by clevermiraz** [comment]
in new `pillow 10.0.0` version remove some method and replace.

For More Info see their Doc: [pillow documentation](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html)

or you can use `pillow 9.5.0`

**Comment by glenn-jocher** [comment]
@clevermiraz thanks for bringing this to our attention. We are aware of the compatibility issue with Pillow 10.0.0 and the error it causes in YOLOv5 related to the missing method 'getsize'. As you correctly mentioned, Pillow 9.5.0 is a suitable alternative that resolves this problem. We are also actively investigating and addressing the compatibility issue with Pillow 10.0.0 to ensure smooth usage for our users. Thank you for your patience and understanding.

**Comment by IshuSinghSE** [comment]
**now in pillow 10 you can use**

Instead of `ImageFont.FreeTypeFont(fontfile, size=55, encoding="unic")` and `getsize(string)`

use `ImageFont.truetype(fontfile, size=55, encoding="unic")` and `getlength(string)`

**Comment by glenn-jocher** [comment]
@IshuSinghSE thanks for sharing the updated usage for Pillow 10! We appreciate your contribution to the YOLOv5 community. Using `ImageFont.truetype(fontfile, size=55, encoding="unic")` and `getlength(string)` instead of `ImageFont.FreeTypeFont(fontfile, size=55, encoding="unic")` and `getsize(string)` is indeed the correct approach for Pillow 10. This information will be helpful for other users encountering the same issue. If you have any further questions or need assistance, feel free to ask.

**Comment by 15738281321** [comment]
> @IshuSinghSE thanks for sharing the updated usage for Pillow 10! We appreciate your contribution to the YOLOv5 community. Using `ImageFont.truetype(fontfile, size=55, encoding="unic")` and `getlength(string)` instead of `ImageFont.FreeTypeFont(fontfile, size=55, encoding="unic")` and `getsize(string)` is indeed the correct approach for Pillow 10. This information will be helpful for other users encountering the same issue. If you have any further questions or need assistance, feel free to ask.

Can you tell me which file should be modified?

**Comment by Adreaming5101** [comment]
我也遇到了同样的问题，将Pillow降到9.5已经解决

**Comment by Adreaming5101** [comment]
I also encountered the same problem, and lowering Pillow to 9.5 has been solved

**Comment by glenn-jocher** [comment]
@Adreaming5101 it's great to hear that downgrading to Pillow 9.5 resolved the issue for you! If you have any further questions or need assistance in the future, please feel free to reach out.

**Comment by IshuSinghSE** [comment]
> > @IshuSinghSE thanks for sharing the updated usage for Pillow 10! We appreciate your contribution to the YOLOv5 community. Using `ImageFont.truetype(fontfile, size=55, encoding="unic")` and `getlength(string)` instead of `ImageFont.FreeTypeFont(fontfile, size=55, encoding="unic")` and `getsize(string)` is indeed the correct approach for Pillow 10. This information will be helpful for other users encountering the same issue. If you have any further questions or need assistance, feel free to ask.
> 
> Can you tell me which file should be modified?

Use getlength() ...

**Comment by glenn-jocher** [comment]
@IshuSinghSE apologies for the confusion earlier. To clarify, the `getlength()` method does not replace `getsize()`. The correct method to use in Pillow 10 for obtaining text size remains `getsize()`. If you're experiencing issues with `getsize()`, please ensure you're using the `ImageFont.truetype()` method to create your font object, as this should still provide the `getsize()` method.

If you're still encountering issues, it might be necessary to review the specific code where the error occurs. However, as a general guideline, you would typically look for the usage of `getsize()` in the file where you're handling font rendering, which is often in the visualization or drawing sections of the code.

If downgrading to Pillow 9.5 has resolved the issue for you, that's a good temporary solution. We will look into updating the YOLOv5 codebase to be compatible with Pillow 10.0.0 and beyond. If you have any further questions or need more assistance, please let us know.

**Comment by romanwolf-git** [comment]
I had the same problem as @uesrs, but downgrading to Pillow 9.5 didn't work for me. In the error that comes from plots.py, `getsize` in line 86 should be replaced by `getbbox` like this:

```
left, top, right, bottom = self.font.getbbox(label)
w = right - left
h = bottom - top
```

Replacing with get_length doesn't work in this particular case, because w and h are needed in the code.

**Comment by jzrzzzzz** [comment]
> I had the same problem as @uesrs, but downgrading to Pillow 9.5 didn't work for me. In the error that comes from plots.py, `getsize` in line 86 should be replaced by `getbbox` like this:
> 
> ```
> left, top, right, bottom = self.font.getbbox(label)
> w = right - left
> h = bottom - top
> ```
> 
> Replacing with get_length doesn't work in this particular case, because w and h are needed in the code.

Thanks@romanwolf-git. The problem doesn't solved with downgrading to Pillow 9.5 but your solution is work for me.

**Comment by jzrzzzzz** [comment]
Thanks @romanwolf-git .The problem doesn't solved with downgrading to Pillow 9.5 but your solution is work for me.
